/**
 * Theme definitions for the Daily Rambam app.
 * Each theme maps CSS variable names to color values.
 *
 * Colors are chosen to be soft/pastel-leaning while maintaining
 * sufficient contrast for accessibility (white text on primary buttons).
 */

import type { ThemeId } from "@/types";

export interface ThemeDefinition {
  id: ThemeId;
  isDark: boolean;
  colors: Record<string, string>;
}

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  teal: {
    id: "teal",
    isDark: false,
    colors: {
      "--color-primary": "#0d9488",
      "--color-primary-dark": "#0f766e",
      "--color-accent": "#f59e0b",
      "--color-alt-date": "#9333ea",
      "--color-bg": "#0d9488",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#f0fdfa",
      "--color-surface-border": "#e5e7eb",
      "--color-text-primary": "#1f2937",
      "--color-text-secondary": "#4b5563",
      "--color-text-muted": "#9ca3af",
      "--color-completion-bg": "#f0fdfa",
      "--color-completion-border": "#99f6e4",
      "--color-completion-accent": "#0d9488",
      "--color-status-normal": "#0d9488",
      "--color-status-other-date": "#dc2626",
      "--color-status-offline": "#f59e0b",
    },
  },
  sky: {
    id: "sky",
    isDark: false,
    colors: {
      "--color-primary": "#0284c7",
      "--color-primary-dark": "#0369a1",
      "--color-accent": "#f59e0b",
      "--color-alt-date": "#e11d48",
      "--color-bg": "#0284c7",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#f0f9ff",
      "--color-surface-border": "#e0e7ef",
      "--color-text-primary": "#1e293b",
      "--color-text-secondary": "#475569",
      "--color-text-muted": "#94a3b8",
      "--color-completion-bg": "#f0f9ff",
      "--color-completion-border": "#bae6fd",
      "--color-completion-accent": "#0284c7",
      "--color-status-normal": "#0284c7",
      "--color-status-other-date": "#e11d48",
      "--color-status-offline": "#f59e0b",
    },
  },
  lavender: {
    id: "lavender",
    isDark: false,
    colors: {
      "--color-primary": "#7c3aed",
      "--color-primary-dark": "#6d28d9",
      "--color-accent": "#06b6d4",
      "--color-alt-date": "#e11d48",
      "--color-bg": "#7c3aed",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#f5f3ff",
      "--color-surface-border": "#e5e1f0",
      "--color-text-primary": "#1f2937",
      "--color-text-secondary": "#4b5563",
      "--color-text-muted": "#9ca3af",
      "--color-completion-bg": "#f5f3ff",
      "--color-completion-border": "#ddd6fe",
      "--color-completion-accent": "#7c3aed",
      "--color-status-normal": "#7c3aed",
      "--color-status-other-date": "#e11d48",
      "--color-status-offline": "#f59e0b",
    },
  },
  rose: {
    id: "rose",
    isDark: false,
    colors: {
      "--color-primary": "#e11d48",
      "--color-primary-dark": "#be123c",
      "--color-accent": "#0d9488",
      "--color-alt-date": "#7c3aed",
      "--color-bg": "#e11d48",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#fff1f2",
      "--color-surface-border": "#f0e0e3",
      "--color-text-primary": "#1f2937",
      "--color-text-secondary": "#4b5563",
      "--color-text-muted": "#9ca3af",
      "--color-completion-bg": "#fff1f2",
      "--color-completion-border": "#fecdd3",
      "--color-completion-accent": "#e11d48",
      "--color-status-normal": "#e11d48",
      "--color-status-other-date": "#9f1239",
      "--color-status-offline": "#f59e0b",
    },
  },
  sage: {
    id: "sage",
    isDark: false,
    colors: {
      "--color-primary": "#059669",
      "--color-primary-dark": "#047857",
      "--color-accent": "#eab308",
      "--color-alt-date": "#dc2626",
      "--color-bg": "#059669",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#ecfdf5",
      "--color-surface-border": "#e0ebe5",
      "--color-text-primary": "#1f2937",
      "--color-text-secondary": "#4b5563",
      "--color-text-muted": "#9ca3af",
      "--color-completion-bg": "#ecfdf5",
      "--color-completion-border": "#a7f3d0",
      "--color-completion-accent": "#059669",
      "--color-status-normal": "#059669",
      "--color-status-other-date": "#dc2626",
      "--color-status-offline": "#f59e0b",
    },
  },
  amber: {
    id: "amber",
    isDark: false,
    colors: {
      "--color-primary": "#d97706",
      "--color-primary-dark": "#b45309",
      "--color-accent": "#7c3aed",
      "--color-alt-date": "#dc2626",
      "--color-bg": "#d97706",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#fffbeb",
      "--color-surface-border": "#e8e0d0",
      "--color-text-primary": "#1f2937",
      "--color-text-secondary": "#4b5563",
      "--color-text-muted": "#9ca3af",
      "--color-completion-bg": "#fffbeb",
      "--color-completion-border": "#fde68a",
      "--color-completion-accent": "#d97706",
      "--color-status-normal": "#d97706",
      "--color-status-other-date": "#dc2626",
      "--color-status-offline": "#0d9488",
    },
  },
  coral: {
    id: "coral",
    isDark: false,
    colors: {
      "--color-primary": "#ea580c",
      "--color-primary-dark": "#c2410c",
      "--color-accent": "#0284c7",
      "--color-alt-date": "#7c3aed",
      "--color-bg": "#ea580c",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#fff7ed",
      "--color-surface-border": "#e8e0db",
      "--color-text-primary": "#1f2937",
      "--color-text-secondary": "#4b5563",
      "--color-text-muted": "#9ca3af",
      "--color-completion-bg": "#fff7ed",
      "--color-completion-border": "#fed7aa",
      "--color-completion-accent": "#ea580c",
      "--color-status-normal": "#ea580c",
      "--color-status-other-date": "#dc2626",
      "--color-status-offline": "#f59e0b",
    },
  },
  dark: {
    id: "dark",
    isDark: true,
    colors: {
      "--color-primary": "#38bdf8",
      "--color-primary-dark": "#0284c7",
      "--color-accent": "#a78bfa",
      "--color-alt-date": "#f472b6",
      "--color-bg": "#0f172a",
      "--color-surface": "#1e293b",
      "--color-surface-glass": "rgba(30,41,59,0.55)",
      "--color-surface-hover": "#334155",
      "--color-surface-border": "#334155",
      "--color-text-primary": "#f1f5f9",
      "--color-text-secondary": "#94a3b8",
      "--color-text-muted": "#64748b",
      "--color-completion-bg": "#0c1a2e",
      "--color-completion-border": "#1e3a5f",
      "--color-completion-accent": "#38bdf8",
      "--color-status-normal": "#38bdf8",
      "--color-status-other-date": "#f472b6",
      "--color-status-offline": "#fbbf24",
    },
  },
  light: {
    id: "light",
    isDark: false,
    colors: {
      "--color-primary": "#44403c",
      "--color-primary-dark": "#292524",
      "--color-accent": "#78716c",
      "--color-alt-date": "#dc2626",
      "--color-bg": "#44403c",
      "--color-surface": "#ffffff",
      "--color-surface-glass": "rgba(255,255,255,0.55)",
      "--color-surface-hover": "#fafaf9",
      "--color-surface-border": "#e7e5e4",
      "--color-text-primary": "#1c1917",
      "--color-text-secondary": "#44403c",
      "--color-text-muted": "#a8a29e",
      "--color-completion-bg": "#f5f5f4",
      "--color-completion-border": "#d6d3d1",
      "--color-completion-accent": "#44403c",
      "--color-status-normal": "#44403c",
      "--color-status-other-date": "#dc2626",
      "--color-status-offline": "#f59e0b",
    },
  },
  oled: {
    id: "oled",
    isDark: true,
    colors: {
      "--color-primary": "#60a5fa",
      "--color-primary-dark": "#3b82f6",
      "--color-accent": "#a78bfa",
      "--color-alt-date": "#fb7185",
      "--color-bg": "#000000",
      "--color-surface": "#0a0a0a",
      "--color-surface-glass": "rgba(10,10,10,0.85)",
      "--color-surface-hover": "#171717",
      "--color-surface-border": "#262626",
      "--color-text-primary": "#fafafa",
      "--color-text-secondary": "#a3a3a3",
      "--color-text-muted": "#737373",
      "--color-completion-bg": "#0a0a0a",
      "--color-completion-border": "#1a1a2e",
      "--color-completion-accent": "#60a5fa",
      "--color-status-normal": "#60a5fa",
      "--color-status-other-date": "#fb7185",
      "--color-status-offline": "#fbbf24",
    },
  },
};

/** Get a theme by ID, falling back to teal */
export function getTheme(id: ThemeId): ThemeDefinition {
  return THEMES[id] ?? THEMES.teal;
}
